"""Re-execute the teaching notebook and hold its stored outputs to what the code produces.

A notebook is documentation that claims to be a transcript. Left alone it becomes the most
convincing kind of stale documentation there is, because the values look like evidence: a
reader has no way to tell a printed digest that is current from one that was current a year
ago. So the outputs committed to the notebook are treated exactly like the golden artifacts:
regenerated by a command, compared by the gate, and never edited by hand.

Cells run in one namespace in this process, in order, with stdout captured per cell, which
is what a kernel does for a linear notebook and needs no kernel to do. Nothing here renders
rich output: every cell in this notebook prints, and a cell that returned a value instead
would be reported rather than quietly ignored.

`--write` stores the outputs. With no argument the outputs are compared and any difference
is a failure.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import sys
import traceback
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = REPO_ROOT / "notebooks" / "from_specification_to_server.ipynb"


class CellFailed(Exception):
    """Raised when a cell does not run at all."""


def _source(cell: dict[str, Any]) -> str:
    """Join a cell's source, which nbformat stores as a list of lines."""
    source = cell.get("source", "")
    return source if isinstance(source, str) else "".join(source)


def _stored(cell: dict[str, Any]) -> str:
    """The stdout stored for a cell, as one string."""
    text: list[str] = []
    for output in cell.get("outputs", []):
        if output.get("output_type") == "stream":
            content = output.get("text", "")
            text.append(content if isinstance(content, str) else "".join(content))
    return "".join(text)


def _run(cells: list[dict[str, Any]]) -> list[str]:
    """Execute every code cell in one namespace and return what each printed."""
    namespace: dict[str, Any] = {"__name__": "__notebook__"}
    captured: list[str] = []
    for index, cell in enumerate(cells):
        if cell.get("cell_type") != "code":
            continue
        buffer = io.StringIO()
        try:
            with contextlib.redirect_stdout(buffer):
                exec(compile(_source(cell), f"<cell {index}>", "exec"), namespace)
        except Exception as error:  # reported with the cell that raised it
            raise CellFailed(
                f"cell {index} raised {type(error).__name__}: {error}\n"
                + "".join(traceback.format_exc(limit=3))
            ) from error
        captured.append(buffer.getvalue())
    return captured


def _stream(text: str) -> dict[str, Any]:
    """One stdout output in the shape nbformat stores it."""
    return {"output_type": "stream", "name": "stdout", "text": text.splitlines(keepends=True)}


def main() -> int:
    """Compare the notebook's stored outputs with what its cells produce, or store them."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Store the outputs produced.")
    arguments = parser.parse_args()

    if not NOTEBOOK.is_file():
        print(f"notebook not found at {NOTEBOOK}", file=sys.stderr)
        return 1
    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    cells = notebook["cells"]

    # The paths inside the notebook are resolved against the working directory, and a reader
    # opens it from `notebooks/`. Run it from there so the gate exercises what they will.
    previous = Path.cwd()
    sys.path.insert(0, str(REPO_ROOT / "src"))
    os.chdir(REPO_ROOT / "notebooks")
    try:
        produced = _run(cells)
    except CellFailed as failure:
        print(f"the notebook does not run:\n{failure}", file=sys.stderr)
        return 1
    finally:
        os.chdir(previous)

    code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
    if arguments.write:
        for cell, text in zip(code_cells, produced, strict=True):
            cell["outputs"] = [_stream(text)] if text else []
            cell["execution_count"] = None
        NOTEBOOK.write_text(
            json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(f"Stored the output of {len(code_cells)} cells in {NOTEBOOK.name}.")
        return 0

    drifted: list[str] = []
    for index, (cell, text) in enumerate(zip(code_cells, produced, strict=True)):
        stored = _stored(cell)
        if stored != text:
            drifted.append(
                f"code cell {index} does not match its stored output.\n"
                f"  stored:   {stored[:200]!r}\n"
                f"  produced: {text[:200]!r}"
            )
    if drifted:
        print(f"{len(drifted)} notebook cell(s) drifted:", file=sys.stderr)
        for report in drifted:
            print(f"  - {report}", file=sys.stderr)
        print(
            "\nRun `python scripts/check_notebook.py --write` to store the current output, "
            "and read the diff before committing it.",
            file=sys.stderr,
        )
        return 1
    print(f"Notebook re-executed; {len(code_cells)} cells match their stored output.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
